name: My-demo-flow
on: workflow_dispatch
jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code.
        uses: actions/checkout@v4

      - name: Print message
        run: echo "hello world"
  Build:
    needs: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Build the app
        run: echo "Building the application"

      - name: Test the application"
        run: echo "Testing the application"
        
